CONNECT COMPANY_PUBLIC/astrongpassword@localhost:1521/COMPANY;

/*
    Check connection availability
*/
SET SERVEROUTPUT ON

DECLARE
  v_service_name VARCHAR2(100);
BEGIN
  SELECT SYS_CONTEXT('USERENV', 'SERVICE_NAME') INTO v_service_name FROM DUAL;
  DBMS_OUTPUT.PUT_LINE('Service Name: ' || v_service_name);
END;
/

-- Add the foreign key constraint FK_NHANVIEN_NHANVIEN
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_NHANVIEN
FOREIGN KEY (MANQL) REFERENCES NHANVIEN (MANV);

-- Add the foreign key constraint FK_NHANVIEN_PHONG
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_PHONG
FOREIGN KEY (PHG) REFERENCES PHONGBAN (MAPB);

-- Add the foreign key constraint FK_PHONGBAN_NHANVIEN
ALTER TABLE PHONGBAN
ADD CONSTRAINT FK_PHONGBAN_NHANVIEN
FOREIGN KEY (TRPHG) REFERENCES NHANVIEN (MANV);

-- Add the foreign key constraint FK_PHANCONG_NHANVIEN
ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_NHANVIEN
FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV);

-- Add the foreign key constraint FK_PHANCONG_DEAN
ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_DEAN
FOREIGN KEY (MADA) REFERENCES DEAN (MADA);

-- Add the foreign key constraint FK_DEAN_PHONGBAN
ALTER TABLE DEAN
ADD CONSTRAINT FK_DEAN_PHONGBAN
FOREIGN KEY (PHONG) REFERENCES PHONGBAN (MAPB);

ALTER TABLE DANGNHAP
ADD CONSTRAINT FK_DANGNHAP_NHANVIEN 
FOREIGN KEY (MANV) REFERENCES NHANVIEN ( MANV );