CONNECT COMPANY_PUBLIC/astrongpassword@localhost:1521/COMPANY;
GRANT NHAN_VIEN to NV001;
GRANT QL_TRUC_TIEP TO QL001;
GRANT EXECUTE ON COMPANY_PUBLIC.QLTT_SELF_PERMISSION_CONSTRAINTS TO QL001;
SELECT * FROM NHANVIEN;

CONNECT NV001/password@localhost:1521/COMPANY;
SELECT * FROM COMPANY_PUBLIC.NHANVIEN;

CONNECT QL001/QLpassword@localhost:1521/COMPANY;
SET SERVEROUTPUT ON;
BEGIN
    DBMS_OUTPUT.PUT_LINE(COMPANY_PUBLIC.QLTT_SELF_PERMISSION_CONSTRAINTS('COMPANY_PUBLIC', 'NHANVIEN'));
END;
/
SELECT * FROM COMPANY_PUBLIC.PHANCONG;

select OBJECT_NAME, POLICY_NAME, ENABLE from user_policies order by OBJECT_NAME asc;