ALTER SYSTEM SET DB_CREATE_FILE_DEST = '/home/oracle/';
SET SERVEROUTPUT ON;

BEGIN
    EXECUTE IMMEDIATE 'CREATE PLUGGABLE DATABASE COMPANY ADMIN USER master IDENTIFIED BY master';
    DBMS_OUTPUT.PUT_LINE('The PDB is created successfully!!');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('The PDB is already exists, so do not create a new one!!');
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE COMPANY OPEN';
    DBMS_OUTPUT.PUT_LINE('Open PDB successfully!!');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('The PDB is already opened, so do not do any operation!!');
END;
/

ALTER SESSION SET CONTAINER = COMPANY;

-- DROP USER COMPANY_PUBLIC CASCADE;
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER COMPANY_PUBLIC IDENTIFIED BY astrongpassword';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE USER TO COMPANY_PUBLIC WITH ADMIN OPTION';
    EXECUTE IMMEDIATE 'GRANT DBA TO COMPANY_PUBLIC WITH ADMIN OPTION';
    EXECUTE IMMEDIATE 'GRANT SELECT ANY DICTIONARY TO COMPANY_PUBLIC WITH ADMIN OPTION';
    EXECUTE IMMEDIATE 'GRANT CONNECT TO COMPANY_PUBLIC WITH ADMIN OPTION';
    
    DBMS_OUTPUT.PUT_LINE('The Public Schema is created successfully!!');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('The Public Schema is already exists, so do not create a new one!!');
END;
/