CONNECT COMPANY_PUBLIC/astrongpassword@localhost:1521/COMPANY;
SET SERVEROUTPUT ON;

GRANT SELECT ON THONGDIEP TO NHAN_VIEN;
GRANT SELECT ON THONGDIEP TO QL_TRUC_TIEP;
GRANT SELECT ON THONGDIEP TO TRUONG_PHONG;
GRANT SELECT ON THONGDIEP TO TAI_CHINH;
GRANT SELECT ON THONGDIEP TO NHAN_SU;
GRANT SELECT ON THONGDIEP TO TRUONG_DEAN;

GRANT INSERT, SELECT ON THONGDIEP TO COMPANY_PUBLIC;

CREATE OR REPLACE FUNCTION messageAccessRight (
  schema_name   IN VARCHAR2,
  object_name   IN VARCHAR2
)
RETURN VARCHAR2
AS
BEGIN
  IF schema_name = 'COMPANY_PUBLIC' AND object_name = 'THONGDIEP' THEN
        RETURN 'MANV = SYS_CONTEXT(''USERENV'', ''SESSION_USER'')';
  END IF;

  RETURN '0=1';
END;
/

BEGIN
  DBMS_RLS.ADD_POLICY(
    object_schema    => 'COMPANY_PUBLIC',
    object_name      => 'THONGDIEP',
    policy_name      => 'MESSAGE_ACCESS_POLICY',
    policy_function  => 'messageAccessRight',
    statement_types  => 'SELECT',
    enable           => TRUE
  );
END;
/

COMMIT;