ALTER SESSION SET "_ORACLE_SCRIPT" = true;
/

CREATE OR REPLACE VIEW USER_LIST AS 
SELECT USER_ID, USERNAME, ACCOUNT_STATUS, LAST_LOGIN 
FROM DBA_USERS;
/

CREATE OR REPLACE VIEW ROLE_LIST AS 
SELECT ROLE_ID, ROLE, AUTHENTICATION_TYPE, COMMON 
FROM DBA_ROLES;
/

CREATE OR REPLACE VIEW TABLE_LIST AS 
SELECT TABLE_NAME, OWNER, STATUS, NUM_ROWS 
FROM DBA_TABLES;
/

CREATE OR REPLACE VIEW VIEW_LIST AS 
SELECT OWNER, VIEW_NAME, EDITIONING_VIEW, READ_ONLY, HAS_SENSITIVE_COLUMN
FROM DBA_VIEWS;
/

CREATE OR REPLACE PROCEDURE CREATE_USER(USER_NAME VARCHAR2, PASS VARCHAR2)
AS
    strSQL VARCHAR2(3000);
BEGIN
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE';
    EXECUTE IMMEDIATE (strSQL);
    strSQL := ' CREATE USER ' || USER_NAME|| ' IDENTIFIED BY '||PASS;
    EXECUTE IMMEDIATE (strSQL);
    strSQL := ' GRANT CONNECT TO ' || USER_NAME ;
    EXECUTE IMMEDIATE (strSQL);
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE';
    EXECUTE IMMEDIATE (strSQL);
END;
/

CREATE OR REPLACE PROCEDURE CREATE_ROLE( ROLE_NAME VARCHAR2)
AS
    strSQL VARCHAR2(3000);
BEGIN
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE';
    EXECUTE IMMEDIATE (strSQL);
    strSQL := ' CREATE ROLE ' || ROLE_NAME;
    EXECUTE IMMEDIATE (strSQL);
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE';
    EXECUTE IMMEDIATE (strSQL);
    
END;
