ALTER SESSION SET "_ORACLE_SCRIPT" = true;
/

CREATE OR REPLACE VIEW USER_LIST AS 
SELECT USER_ID, USERNAME, ACCOUNT_STATUS, LAST_LOGIN 
FROM DBA_USERS;
/

CREATE OR REPLACE VIEW ROLE_LIST AS 
SELECT ROLE_ID, ROLE, AUTHENTICATION_TYPE, COMMON 
FROM DBA_ROLES;
/

CREATE OR REPLACE VIEW TABLE_LIST AS 
SELECT TABLE_NAME, OWNER, STATUS, NUM_ROWS 
FROM DBA_TABLES;
/

CREATE OR REPLACE VIEW VIEW_LIST AS 
SELECT OWNER, VIEW_NAME, EDITIONING_VIEW, READ_ONLY, HAS_SENSITIVE_COLUMN
FROM DBA_VIEWS;
/