CONNECT COMPANY_PUBLIC/astrongpassword@localhost:1521/COMPANY;
grant NHAN_VIEN to NV001;
REVOKE EXECUTE ON NHANVIEN_PERMISSION_CONSTRAINTS ON NV001;
SELECT * FROM NHANVIEN;

CONNECT NV001/password@localhost:1521/COMPANY;
SELECT * FROM COMPANY_PUBLIC.NHANVIEN;